
                (function() {
                    var nodeEnv = typeof require !== 'undefined' && typeof process !== 'undefined';
                    var __module = nodeEnv ? module : {exports:{}};
                    var __filename = 'preview-scripts/__qc_index__.js';
                    var __require = nodeEnv ? function (request) {
                        return cc.require(request);
                    } : function (request) {
                        return __quick_compile_project__.require(request, __filename);
                    };
                    function __define (exports, require, module) {
                        if (!nodeEnv) {__quick_compile_project__.registerModule(__filename, module);}
require('./assets/framework/on/mEvent');
require('./assets/framework/on/mEventMgr');
require('./assets/framework/script/ui-base');
require('./assets/framework/script/ui-manager');
require('./assets/scripts/Msg');
require('./assets/scripts/UIPrivacy');
require('./assets/scripts/audioNameMgr');
require('./assets/scripts/caijiTools');
require('./assets/scripts/dontDestroy');
require('./assets/scripts/game/E10controller');
require('./assets/scripts/game/E18controller');
require('./assets/scripts/game/E1controller');
require('./assets/scripts/game/E20controller');
require('./assets/scripts/game/E29controller');
require('./assets/scripts/game/E2controller');
require('./assets/scripts/game/E39Laser');
require('./assets/scripts/game/E39controller');
require('./assets/scripts/game/Events');
require('./assets/scripts/game/FX_E10');
require('./assets/scripts/game/FX_flagThunder');
require('./assets/scripts/game/FX_revive');
require('./assets/scripts/game/GameManager');
require('./assets/scripts/game/animationState');
require('./assets/scripts/game/arrow');
require('./assets/scripts/game/bigSquidController');
require('./assets/scripts/game/cameraControl');
require('./assets/scripts/game/coinDrop');
require('./assets/scripts/game/damageEffect');
require('./assets/scripts/game/damageLabel');
require('./assets/scripts/game/damageTipPool');
require('./assets/scripts/game/dropBloodBottle');
require('./assets/scripts/game/enemyAnimation');
require('./assets/scripts/game/enemyBase');
require('./assets/scripts/game/enemyDieEffect');
require('./assets/scripts/game/enemyHitCollider');
require('./assets/scripts/game/enemySpawn');
require('./assets/scripts/game/firePillarCollider');
require('./assets/scripts/game/ladyBug');
require('./assets/scripts/game/ladyBugFx');
require('./assets/scripts/game/levelInit');
require('./assets/scripts/game/miniBossController');
require('./assets/scripts/game/miniBossFlag');
require('./assets/scripts/game/playerCollider');
require('./assets/scripts/game/playerColliderAttack1');
require('./assets/scripts/game/playerColliderAttack2');
require('./assets/scripts/game/playerColliderAttack3');
require('./assets/scripts/game/playerColliderJumpHit');
require('./assets/scripts/game/playerController');
require('./assets/scripts/game/playerPandant');
require('./assets/scripts/game/playerSpawn');
require('./assets/scripts/game/portal');
require('./assets/scripts/game/reviveFx');
require('./assets/scripts/game/rock');
require('./assets/scripts/game/shaderController');
require('./assets/scripts/game/shuriken');
require('./assets/scripts/game/skillPool');
require('./assets/scripts/game/spawnEnemy');
require('./assets/scripts/game/spiderlingController');
require('./assets/scripts/game/swordItem');
require('./assets/scripts/game/swordItem2');
require('./assets/scripts/game/swordRain');
require('./assets/scripts/game/swordRainCollider');
require('./assets/scripts/game/swordSmoke');
require('./assets/scripts/game/thunderBall_burst');
require('./assets/scripts/game/thunder_burstParent');
require('./assets/scripts/game/thunder_chase');
require('./assets/scripts/game/thunder_jolt');
require('./assets/scripts/game/ui/Joystick');
require('./assets/scripts/game/ui/bossHp');
require('./assets/scripts/game/ui/buffPopup');
require('./assets/scripts/game/ui/losePanel');
require('./assets/scripts/game/ui/pausePanel');
require('./assets/scripts/game/ui/playerControlEvent');
require('./assets/scripts/game/ui/playerHp');
require('./assets/scripts/game/ui/testLabel');
require('./assets/scripts/game/ui/uiManager');
require('./assets/scripts/game/ui/winPanel');
require('./assets/scripts/initLoading');
require('./assets/scripts/main/UiSign');
require('./assets/scripts/main/audioManager');
require('./assets/scripts/main/choseLevelPanel');
require('./assets/scripts/main/levelItem');
require('./assets/scripts/main/mainMenu');
require('./assets/scripts/main/upgradePanel');
require('./assets/scripts/sdk/Constant');
require('./assets/scripts/sdk/_bytedance');
require('./assets/scripts/sdk/_oppo');
require('./assets/scripts/sdk/_qq');
require('./assets/scripts/sdk/_vivo');
require('./assets/scripts/sdk/_wechat');
require('./assets/scripts/sdk/ad');
require('./assets/scripts/sdk/data');
require('./assets/scripts/sdk/type');
require('./assets/scripts/test');
require('./assets/scripts/uiBase');
require('./assets/syyx_sdk/3rd/tpfsdk/3rd/md5');
require('./assets/syyx_sdk/3rd/tpfsdk/communication/httputils');
require('./assets/syyx_sdk/3rd/tpfsdk/sdk/tpfclientsdk');
require('./assets/syyx_sdk/3rd/tpfsdk/sdk/tpfconfig');
require('./assets/syyx_sdk/3rd/tpfsdk/sdk/tpfstat');
require('./assets/syyx_sdk/configs/syyx_sdk_config');
require('./assets/syyx_sdk/configs/syyx_sdk_enum');
require('./assets/syyx_sdk/controller/ad/ad_banner');
require('./assets/syyx_sdk/controller/ad/ad_block');
require('./assets/syyx_sdk/controller/ad/ad_native_icon');
require('./assets/syyx_sdk/controller/ad/ad_native_inner_interstitial');
require('./assets/syyx_sdk/controller/ad/ad_native_interstitial');
require('./assets/syyx_sdk/controller/ad/ad_oppo_banner');
require('./assets/syyx_sdk/controller/ad/syyx_adv_manager');
require('./assets/syyx_sdk/controller/ctr_test/syyx_ctr_manager');
require('./assets/syyx_sdk/controller/syyx_cc_ui_manager');
require('./assets/syyx_sdk/controller/syyx_manager');
require('./assets/syyx_sdk/export_sdk');
require('./assets/syyx_sdk/model/model');
require('./assets/syyx_sdk/syyx_sdk_api');
require('./assets/syyx_sdk/syyx_ui/ad/syyx_ui_banner');
require('./assets/syyx_sdk/syyx_ui/ad/syyx_ui_inner_interstitial');
require('./assets/syyx_sdk/syyx_ui/ad/syyx_ui_interstitial');
require('./assets/syyx_sdk/syyx_ui/ad/syyx_ui_native_icon');
require('./assets/syyx_sdk/syyx_ui/ad/syyx_ui_toast');
require('./assets/syyx_sdk/syyx_ui/ctr_test/syyx_ui_ctr');
require('./assets/syyx_sdk/syyx_ui/ctr_test/syyx_ui_ctr_item');
require('./assets/syyx_sdk/utils/syyx_api');
require('./assets/syyx_sdk/utils/syyx_sdk_utils');

                    }
                    if (nodeEnv) {
                        __define(__module.exports, __require, __module);
                    }
                    else {
                        __quick_compile_project__.registerModuleFunc(__filename, function () {
                            __define(__module.exports, __require, __module);
                        });
                    }
                })();